[package]
name = "animejoya"
version = "0.1.0"
edition = "2021"

[lib]
name = "animejoya_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = [] }
anyhow = "1.0.104"
reqwest = { version = "0.13.4", default-features = false, features = ["stream", "cookies", "gzip", "brotli", "rustls", "charset", "json", "form"] }
scraper = "0.27.0"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
percent-encoding = "2.3.2"
tokio = { version = "1.53.1", features = ["fs", "io-util", "sync", "process"] }
futures-util = "0.3.34"

[profile.release]
opt-level = 2
lto = true
strip = true
